### ISSUE TITLE
Feature Request - Support BPM along with seconds.

### ISSUE THREAD

**Issue by ImDaRealAni** [GrandMoff100/Wallaby#1]
I would like to request a feature that allows one to set a BPM at the beginning of the project. The \play will use the number provide to play the note for the number of beats (with the given BPM). 

Support for seconds should remain.

**Comment by GrandMoff100** [comment]
Hmmm, I think supporting both would get very confusing user wise, and supporting counts would make it easier to support exporting to sheet music. Is there a reason why seconds should remain?

**Comment by ImDaRealAni** [comment]
Good point. Counting by seconds is equivalent to 60 BPM. If you ever add a little documentation (as a user guide), perhaps you could mention that. Or set it as the default tempo for a skeleton project.

**Comment by ImDaRealAni** [comment]
If you would like, once you push your first commit of what you have currently, I can try implementing support for BPM.

**Comment by GrandMoff100** [comment]
👍

**Comment by GrandMoff100** [comment]
@ImDaRealAni I think I've built enough of the infrastructure in place that you can see the tempo environment in `environments.py`. Support for seconds has been dropped.
